INDEX_MAPPING = {
    "ASX200":    "^AXJO",      # ASX 200 (Australian)
    "CH20":      "^SSMI",      # CH20 (Swiss Market Index)
    "DE40":      "^GDAXI",     # DAX (Germany)
    "ES35":      "^IBEX",      # IBEX 35 (Spain)
    "EU50":      "^STOXX50E",  # Euro Stoxx 50 (Europe)
    "FR40":      "^FCHI",      # CAC 40 (France)
    "GB100":     "^FTSE",      # FTSE 100 (UK)
    "HK50":      "^HSI",       # Hang Seng (Hong Kong)
    "IBOVESPA":  "^BVSP",      # Bovespa (Brazil)
    "IPC":       "^MXX",       # IPC (Mexico)
    "IT40":      "^FTMIB",     # FTSE MIB (Italy)
    "JP225":     "^N225",      # Nikkei 225 (Japan)
    "MOEX":      "IMOEX.ME",   # MOEX (Russia)
    "NL25":      "^AEX",       # AEX (Netherlands)
    "NZX 50":    "^NZ50",      # NZX 50 (New Zealand)
    "SAALL":     "^JN0U.JO",   # JSE All Share (South Africa; verify ticker)
    "SENSEX":    "^BSESN",     # BSE Sensex (India)
    "SHANGHAI":  "000001.SS",  # SSE Composite (Shanghai)
    "STI":       "^STI",       # Straits Times (Singapore)
    "TSX":       "^GSPTSE",    # TSX (Canada)
    "US100":     "^NDX",       # Nasdaq 100 (USA)
    "US30":      "^DJI",       # Dow 30 (USA)
    "US500":     "^GSPC"       # S&P 500 (USA)
}
