IndustryMap = {
    # Basic Materials
    "agricultural-inputs": "Agricultural Inputs",
    "aluminum": "Industrial Metals",
    "building-materials": "Building Materials",
    "chemicals": "Chemicals",
    "coking-coal": "Coal",
    "copper": "Industrial Metals",
    "gold": "Gold",
    "lumber-wood-production": "Lumber & Wood Production",
    "other-industrial-metals-mining": "Industrial Metals",
    "other-precious-metals-mining": "Other Precious Metals & Mining",
    "paper-paper-products": "Paper & Paper Products",
    "silver": "Silver",
    "specialty-chemicals": "Chemicals",
    "steel": "Industrial Metals",
    "thermal-coal": "Coal",
    "uranium": "Uranium",

    # Communication / Media
    "advertising-agencies": "Advertising Agencies",
    "broadcasting": "Broadcasting",
    "electronic-gaming-multimedia": "Electronic Gaming & Multimedia",
    "entertainment": "Entertainment",
    "internet-content-information": "Internet Content & Information",
    "publishing": "Publishing",
    "telecom-services": "Telecom Services",

    # Consumer / Retail
    "apparel-manufacturing": "Apparel/Textile Manufacturing",
    "apparel-retail": "Apparel Retail",
    "auto-manufacturers": "Auto Manufacturers",
    "auto-parts": "Auto Parts",
    "auto-truck-dealerships": "Auto & Truck Dealerships",
    "department-stores": "Department Stores",
    "footwear-accessories": "Footwear & Accessories",
    "furnishings-fixtures-appliances": "Furnishings, Fixtures & Appliances",
    "gambling": "Gambling",
    "home-improvement-retail": "Home Improvement Retail",
    "internet-retail": "Internet Retail",
    "leisure": "Leisure",
    "lodging": "Lodging",
    "luxury-goods": "Luxury Goods",
    "packaging-containers": "Packaging & Containers",
    "personal-services": "Personal Services",
    "recreational-vehicles": "Recreational Vehicles",
    "residential-construction": "Residential Construction",
    "resorts-casinos": "Resorts & Casinos",
    "restaurants": "Restaurants",
    "specialty-retail": "Specialty Retail",
    "textile-manufacturing": "Apparel/Textile Manufacturing",
    "travel-services": "Travel Services",

    # Food, Beverages, Tobacco
    "beverages-brewers": "Beverages - Alcoholic",
    "beverages-non-alcoholic": "Beverages - Non-Alcoholic",
    "beverages-wineries-distilleries": "Beverages - Alcholic",
    "confectioners": "Confectioners",
    "discount-stores": "Discount Stores",
    "education-training-services": "Education & Training Services",
    "farm-products": "Farm Products",
    "food-distribution": "Food Distribution",
    "grocery-stores": "Grocery Stores",
    "household-personal-products": "Household & Personal Products",
    "packaged-foods": "Packaged Foods",
    "tobacco": "Tobacco",

    # Energy
    "oil-gas-drilling": "Oil & Gas",
    "oil-gas-e-p": "Oil & Gas",
    "oil-gas-equipment-services": "Oil & Gas",
    "oil-gas-integrated": "Oil & Gas",
    "oil-gas-midstream": "Oil & Gas",
    "oil-gas-refining-marketing": "Oil & Gas",

    # Financials
    "asset-management": "Asset Management",
    "banks-diversified": "Banks",
    "banks-regional": "Banks",
    "capital-markets": "Capital Markets",
    "credit-services": "Credit Services",
    "financial-conglomerates": "Financial Conglomerates",
    "financial-data-stock-exchanges": "Financial Data & Stock Exchanges",
    "insurance-brokers": "Insurance",
    "insurance-diversified": "Insurance",
    "insurance-life": "Insurance",
    "insurance-property-casualty": "Insurance",
    "insurance-reinsurance": "Insurance",
    "insurance-specialty": "Insurance",
    "mortgage-finance": "Mortgage Finance",
    "shell-companies": "Shell Companies",

    # Healthcare
    "biotechnology": "Biotechnology",
    "diagnostics-research": "Diagnostics & Research",
    "drug-manufacturers-general": "Drug Manufacturers",
    "drug-manufacturers-specialty-generic": "Drug Manufacturers",
    "health-information-services": "Health Information Services",
    "healthcare-plans": "Healthcare Plans",
    "medical-care-facilities": "Medical Care Facilities",
    "medical-devices": "Medical Devices",
    "medical-distribution": "Medical Distribution",
    "medical-instruments-supplies": "Medical Instruments & Supplies",
    "pharmaceutical-retailers": "Pharmaceutical Retailers",

    # Industrials
    "aerospace-defense": "Aerospace & Defense",
    "airlines": "Airlines, Airports & Air Services",
    "airports-air-services": "Airlines, Airports & Air Services",
    "building-products-equipment": "Building Products & Equipment",
    "business-equipment-supplies": "Business Equipment & Supplies",
    "conglomerates": "Conglomerates",
    "consulting-services": "Consulting Services",
    "electrical-equipment-parts": "Electrical Equipment & Parts",
    "engineering-construction": "Engineering & Construction",
    "farm-heavy-construction-machinery": "Farm & Heavy Construction Machinery",
    "industrial-distribution": "Industrial Distribution",
    "infrastructure-operations": "Infrastructure Operations",
    "integrated-freight-logistics": "Integrated Freight & Logistics",
    "marine-shipping": "Marine Shipping",
    "metal-fabrication": "Metal Fabrication",
    "pollution-treatment-controls": "Pollution & Treatment Controls",
    "railroads": "Railroads",
    "rental-leasing-services": "Rental & Leasing Services",
    "security-protection-services": "Security & Protection Services",
    "specialty-business-services": "Specialty Business Services",
    "specialty-industrial-machinery": "Specialty Industrial Machinery",
    "staffing-employment-services": "Staffing & Employment Services",
    "tools-accessories": "Tools & Accessories",
    "trucking": "Trucking",
    "waste-management": "Waste Management",

    # Real Estate
    "real-estate-development": "Real Estate",
    "real-estate-diversified": "Real Estate",
    "real-estate-services": "Real Estate Services",
    "reit-diversified": "REIT",
    "reit-healthcare-facilities": "REIT",
    "reit-hotel-motel": "REIT",
    "reit-industrial": "REIT",
    "reit-mortgage": "REIT",
    "reit-office": "REIT",
    "reit-residential": "REIT",
    "reit-retail": "REIT",
    "reit-specialty": "REIT",

    # Technology
    "communication-equipment": "Communication Equipment",
    "computer-hardware": "Computer Hardware",
    "consumer-electronics": "Consumer Electronics",
    "electronic-components": "Electronic Components",
    "electronics-computer-distribution": "Electronics & Computer Distribution",
    "information-technology-services": "Information Technology Services",
    "scientific-technical-instruments": "Scientific & Technical Instruments",
    "semiconductor-equipment-materials": "Semiconductor",
    "semiconductors": "Semiconductors",
    "software-application": "Software - Application",
    "software-infrastructure": "Software - Infrastructure",
    "solar": "Solar",

    # Utilities
    "utilities-diversified": "Utilities - Diversified",
    "utilities-independent-power-producers": "Utilities - Independent Power Producers",
    "utilities-regulated-electric": "Utilities - Regulated Electric",
    "utilities-regulated-gas": "Utilities - Regulated Gas",
    "utilities-regulated-water": "Utilities - Regulated Water",
    "utilities-renewable": "Utilities - Renewable",
}
